package tui

import (
	"fmt"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/bubbles/viewport"
	"github.com/charmbracelet/lipgloss"
)

type OutputScreenModel struct {
	config      Config
	viewport    viewport.Model
	width       int
	height      int
	showHelp    bool
	output      string
	copySuccess bool
}

func NewOutputScreenModel(config Config) OutputScreenModel {
	vp := viewport.New(80, 20)
	vp.Style = lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).
		BorderForeground(primaryColor).
		Padding(1, 1)

	output := generateOutput(config)

	return OutputScreenModel{
		config:      config,
		viewport:    vp,
		width:       80,
		height:      24,
		showHelp:    false,
		output:      output,
		copySuccess: false,
	}
}

func (m OutputScreenModel) Init() tea.Cmd {
	return nil
}

func (m OutputScreenModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c":
			return m, tea.Quit
		case "c":
			// Copy to clipboard (simulated)
			m.copySuccess = true
			return m, tea.Tick(time.Second*2, func(t time.Time) tea.Msg {
				return CopyResetMsg{}
			})
		case "s":
			// Save to file (simulated)
			m.copySuccess = true
			return m, tea.Tick(time.Second*2, func(t time.Time) tea.Msg {
				return CopyResetMsg{}
			})
		case "esc":
			// Go back to review
			return m, func() tea.Msg { return ScreenTransitionMsg{From: StateOutput, To: StateReview} }
		case "?":
			m.showHelp = !m.showHelp
			return m, nil
		}
	case CopyResetMsg:
		m.copySuccess = false
	case tea.WindowSizeMsg:
		m.width, m.height = msg.Width, msg.Height
		m.viewport.Width = m.width - 4
		m.viewport.Height = m.height - 10
		m.viewport.GotoTop()
	}

	var cmd tea.Cmd
	m.viewport, cmd = m.viewport.Update(msg)
	return m, cmd
}

type CopyResetMsg struct{}

func (m OutputScreenModel) View() string {
	title := titleStyle.Render("Generated Configuration")
	subtitle := subtitleStyle.Render(fmt.Sprintf("Output format: %s", m.config.OutputMode))

	// Set content
	m.viewport.SetContent(m.output)

	// Status message
	var statusMsg string
	if m.copySuccess {
		statusMsg = successStyle.Render("✓ Copied to clipboard!")
	} else {
		statusMsg = HelpText("Options: (C)opy to clipboard • (S)ave to file • (Esc)Back • (Q)uit")
	}

	// Main content layout
	mainContent := lipgloss.JoinVertical(
		lipgloss.Left,
		title,
		subtitle,
		"",
		m.viewport.View(),
		"",
		statusMsg,
	)

	// Help footer
	var helpText string
	if m.showHelp {
		helpText = HelpText("↑/↓: Scroll • C: Copy • S: Save • Esc: Back • Q: Quit")
	} else {
		helpText = footerStyle.Render("?: Show help")
	}

	fullContent := lipgloss.JoinVertical(lipgloss.Left, mainContent, "", helpText)

	return lipgloss.NewStyle().
		Width(m.width).
		Align(lipgloss.Center).
		Render(fullContent)
}

func generateOutput(config Config) string {
	switch config.OutputMode {
	case OutputYAML:
		return generateYAML(config)
	case OutputEnvFile:
		return generateEnvFile(config)
	case OutputComposeBlock:
		return generateComposeBlock(config)
	default:
		return generateYAML(config)
	}
}

func generateYAML(config Config) string {
	var lines []string

	lines = append(lines, "# bloop-tunnel configuration")
	lines = append(lines, "# Generated by bloop-tunnel TUI")
	lines = append(lines, "")
	lines = append(lines, "# Connection settings")
	lines = append(lines, fmt.Sprintf("control_plane_url: %s", config.ControlPlaneURL))
	lines = append(lines, fmt.Sprintf("relay_url: %s", config.RelayURL))
	lines = append(lines, fmt.Sprintf("auth_token_env: %s", config.AuthTokenEnv))

	if config.EnrollmentToken != "" {
		lines = append(lines, fmt.Sprintf("enrollment_token: %s", config.EnrollmentToken))
	}
	if config.EnrollmentTokenEnv != "" {
		lines = append(lines, fmt.Sprintf("enrollment_token_env: %s", config.EnrollmentTokenEnv))
	}

	lines = append(lines, "")
	lines = append(lines, "# Reconnect settings")
	lines = append(lines, "reconnect:")
	lines = append(lines, fmt.Sprintf("  initial_delay_ms: %d", config.Reconnect.InitialDelayMs))
	lines = append(lines, fmt.Sprintf("  max_delay_ms: %d", config.Reconnect.MaxDelayMs))

	if len(config.Tunnels) > 0 {
		lines = append(lines, "")
		lines = append(lines, "# Tunnels")
		lines = append(lines, "tunnels:")

		for _, tunnel := range config.Tunnels {
			lines = append(lines, fmt.Sprintf("  - name: %s", tunnel.Name))
			lines = append(lines, fmt.Sprintf("    local_ip: %s", tunnel.LocalIP))
			lines = append(lines, fmt.Sprintf("    local_port: %d", tunnel.LocalPort))

			if tunnel.Hostname != "" {
				lines = append(lines, fmt.Sprintf("    hostname: %s", tunnel.Hostname))
			}

			lines = append(lines, fmt.Sprintf("    access: %s", tunnel.Access))

			if tunnel.Access == "basic_auth" {
				lines = append(lines, fmt.Sprintf("    basic_auth:"))
				lines = append(lines, fmt.Sprintf("      username: %s", tunnel.BasicAuth.Username))
				if tunnel.BasicAuth.PasswordEnv != "" {
					lines = append(lines, fmt.Sprintf("      password_env: %s", tunnel.BasicAuth.PasswordEnv))
				}
			} else if tunnel.Access == "token_protected" && tunnel.TokenEnv != "" {
				lines = append(lines, fmt.Sprintf("    token_env: %s", tunnel.TokenEnv))
			}
		}
	}

	return strings.Join(lines, "\n")
}

func generateEnvFile(config Config) string {
	var lines []string

	lines = append(lines, "# bloop-tunnel environment variables")
	lines = append(lines, "# Generated by bloop-tunnel TUI")
	lines = append(lines, "")

	lines = append(lines, fmt.Sprintf("BLOOP_CONTROL_PLANE_URL=%s", config.ControlPlaneURL))
	lines = append(lines, fmt.Sprintf("BLOOP_RELAY_URL=%s", config.RelayURL))

	if config.EnrollmentToken != "" {
		lines = append(lines, fmt.Sprintf("BLOOP_ENROLLMENT_TOKEN=%s", config.EnrollmentToken))
	}

	if len(config.Tunnels) > 0 {
		for i, tunnel := range config.Tunnels {
			lines = append(lines, fmt.Sprintf("BLOOP_TUNNEL_%d_NAME=%s", i, tunnel.Name))
			lines = append(lines, fmt.Sprintf("BLOOP_TUNNEL_%d_LOCAL=%s:%d", i, tunnel.LocalIP, tunnel.LocalPort))
			lines = append(lines, fmt.Sprintf("BLOOP_TUNNEL_%d_ACCESS=%s", i, tunnel.Access))
		}
	}

	return strings.Join(lines, "\n")
}

func generateComposeBlock(config Config) string {
	var lines []string

	lines = append(lines, "# bloop-tunnel docker-compose service")
	lines = append(lines, "# Add this to your docker-compose.yml")
	lines = append(lines, "")
	lines = append(lines, "services:")
	lines = append(lines, "  bloop-tunnel:")
	lines = append(lines, "    image: bloop/tunnel-client:latest")
	lines = append(lines, "    environment:")
	lines = append(lines, fmt.Sprintf("      - BLOOP_CONTROL_PLANE_URL=%s", config.ControlPlaneURL))
	lines = append(lines, fmt.Sprintf("      - BLOOP_RELAY_URL=%s", config.RelayURL))

	if config.EnrollmentToken != "" {
		lines = append(lines, fmt.Sprintf("      - BLOOP_ENROLLMENT_TOKEN=%s", config.EnrollmentToken))
	}

	if config.EnrollmentTokenEnv != "" {
		lines = append(lines, fmt.Sprintf("      - %s", config.EnrollmentTokenEnv))
	} else {
		lines = append(lines, "      - BLOOP_CLIENT_TOKEN")
	}

	lines = append(lines, "    ports:")

	for _, tunnel := range config.Tunnels {
		lines = append(lines, fmt.Sprintf("      - \"%d:%d\"", tunnel.LocalPort, tunnel.LocalPort))
	}

	lines = append(lines, "    restart: unless-stopped")

	return strings.Join(lines, "\n")
}
